site_name: Docs
theme:
  name: material
  logo: assets/paxcounter_logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: indigo
nav:
  - Intro: index.md
  - Hardware: hardware.md
  - Getting Started: getting-started.md
  - Display & LED: display-led.md
  - Legal note: legalnote.md
  - Additions: additions.md
  - Integrations: integrations.md
  - Payload Format: payloadformat.md
  - Remote control: remotecontrol.md
  - Licence & Credits: license-credits.md
  - Releases: releases.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

repo_url: https://github.com/cyberman54/ESP32-Paxcounter
